table Country
	lineageTag: 79ea43f6-1a5d-45a3-a38e-8712bb2ad948

	column COUNTRY_ID
		dataType: double
		isHidden
		lineageTag: 40957b35-184c-4749-8c92-dca8af9b8f87
		summarizeBy: none
		sourceColumn: COUNTRY_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Country Code'
		dataType: string
		lineageTag: 8bce59fe-029e-47d8-8f32-3cfaa5c98ae7
		summarizeBy: none
		sourceColumn: Country Code

		annotation SummarizationSetBy = Automatic

	column 'Country Description'
		dataType: string
		lineageTag: 6afeec95-c99d-4a02-b9e7-5cf0499d4698
		summarizeBy: none
		sourceColumn: Country Description

		annotation SummarizationSetBy = Automatic

	partition Country = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"381214d4-ea63-4a86-87da-8aebf81978ae" = Workspaces{[workspaceId="381214d4-ea63-4a86-87da-8aebf81978ae"]}[Data],
				    #"c8f09baa-dbd9-401b-8d55-1801f53ef645" = #"381214d4-ea63-4a86-87da-8aebf81978ae"{[dataflowId="c8f09baa-dbd9-401b-8d55-1801f53ef645"]}[Data],
				    Country_ = #"c8f09baa-dbd9-401b-8d55-1801f53ef645"{[entity="Country",version=""]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(Country_,{"COUNTRY_ID", "Country Code", "Country Description"})
				in
				    #"Removed Other Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

