table Date
	lineageTag: 1313affa-9736-46f5-bd4b-62a3c46e2b8d

	column DATE_KEY
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 360c7307-25a3-4ed3-8c22-f0bc942e609d
		summarizeBy: none
		sourceColumn: DATE_KEY

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Fiscal Week Code'
		dataType: double
		lineageTag: 4ff06795-bd6e-4432-9805-29c52434d346
		summarizeBy: count
		sourceColumn: Fiscal Week Code

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fiscal Month Code'
		dataType: double
		lineageTag: d0496037-1fcb-423a-b910-eece3b066ee8
		summarizeBy: count
		sourceColumn: Fiscal Month Code

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fiscal Quarter Code'
		dataType: double
		lineageTag: f4d359b1-5ab9-40fb-9214-43f49c37b638
		summarizeBy: count
		sourceColumn: Fiscal Quarter Code

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fiscal Half Code'
		dataType: double
		lineageTag: 9e1457de-7d14-420d-a831-ec6fa71de2ed
		summarizeBy: count
		sourceColumn: Fiscal Half Code

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fiscal Year Code'
		dataType: double
		lineageTag: 5e1e31b9-726a-447e-9e3a-3a587b6dfecf
		summarizeBy: count
		sourceColumn: Fiscal Year Code

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Pnl Year Code'
		dataType: double
		lineageTag: d3770fc4-4728-4df6-8b15-04a532bf2733
		summarizeBy: count
		sourceColumn: Pnl Year Code

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Pnl Quarter Code'
		dataType: double
		lineageTag: 8e1061d5-c6c9-4990-9e9b-1d087dffef65
		summarizeBy: count
		sourceColumn: Pnl Quarter Code

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Pnl Period Code'
		dataType: double
		lineageTag: be203b87-5f8d-4c42-bb99-b6a8e5859c2f
		summarizeBy: count
		sourceColumn: Pnl Period Code

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Pnl Calendar Year Code'
		dataType: double
		lineageTag: 1915939a-1f4a-4a08-8dbe-79babb4b5522
		summarizeBy: count
		sourceColumn: Pnl Calendar Year Code

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Pnl Calendar Month Code'
		dataType: double
		lineageTag: cba6980c-c2e3-4c14-8c49-b38317e1d7c7
		summarizeBy: count
		sourceColumn: Pnl Calendar Month Code

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Day Of Fiscal Week'
		dataType: double
		lineageTag: a097f300-8d2f-4874-a6cd-30e8a74daf8a
		summarizeBy: sum
		sourceColumn: Day Of Fiscal Week

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Day Of Fiscal Month'
		dataType: double
		lineageTag: 912eb146-6af3-4d17-be6d-ad04b44b70b1
		summarizeBy: sum
		sourceColumn: Day Of Fiscal Month

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Day Of Fiscal Quarter'
		dataType: double
		lineageTag: c1f236c5-20fc-4ff2-9cda-8ec378e35b3a
		summarizeBy: sum
		sourceColumn: Day Of Fiscal Quarter

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Day Of Fiscal Half'
		dataType: double
		lineageTag: 5ef7b43f-9ff9-4c66-bfb5-c7f1fac1c991
		summarizeBy: sum
		sourceColumn: Day Of Fiscal Half

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Day Of Fiscal Year'
		dataType: double
		lineageTag: baf13da4-362a-49b9-a97d-bfbe94e63ed6
		summarizeBy: sum
		sourceColumn: Day Of Fiscal Year

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fiscal Week Of Fiscal Year'
		dataType: double
		lineageTag: 225d1b66-bc32-4703-b1b3-bc0827694d89
		summarizeBy: sum
		sourceColumn: Fiscal Week Of Fiscal Year

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fiscal Week Start Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: b7e71f86-156a-4674-b319-42fbc0e24b31
		summarizeBy: none
		sourceColumn: Fiscal Week Start Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fiscal Week Of Fiscal Quarter'
		dataType: double
		lineageTag: 8630d200-6e5c-4ab7-859b-df977984e88f
		summarizeBy: sum
		sourceColumn: Fiscal Week Of Fiscal Quarter

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fiscal Week Of Fiscal Half'
		dataType: double
		lineageTag: 0bc40b62-e4ab-4d3f-b217-91dabca84fa4
		summarizeBy: sum
		sourceColumn: Fiscal Week Of Fiscal Half

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fiscal Week End Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: d575d0b4-7b35-4c09-aa16-3870990689f8
		summarizeBy: none
		sourceColumn: Fiscal Week End Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fiscal Week Name'
		dataType: string
		lineageTag: 5dc94035-ff47-4700-9800-9eaebfd17bf7
		summarizeBy: none
		sourceColumn: Fiscal Week Name

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Week Of Fiscal Month'
		dataType: double
		lineageTag: 229cca92-ba77-4d9d-84c1-98e1fb28bc3d
		summarizeBy: sum
		sourceColumn: Fiscal Week Of Fiscal Month

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fiscal Month Start Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 13298cd8-3227-4779-82f3-b92fb3c9c32e
		summarizeBy: none
		sourceColumn: Fiscal Month Start Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fiscal Month Name'
		dataType: string
		lineageTag: 816df6ca-dcfd-4320-820d-6b2a12ab1c9e
		summarizeBy: none
		sourceColumn: Fiscal Month Name

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Month Time Span'
		dataType: double
		lineageTag: a56842c2-9273-4cf7-a5c6-7ea13d2fa24b
		summarizeBy: sum
		sourceColumn: Fiscal Month Time Span

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fiscal Month Of Fiscal Quarter'
		dataType: double
		lineageTag: be633d32-c39e-443f-929d-7dec23a5e967
		summarizeBy: sum
		sourceColumn: Fiscal Month Of Fiscal Quarter

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fiscal Month Of Fiscal Year'
		dataType: double
		lineageTag: 1010cdff-066f-4ef3-9453-490100d61120
		summarizeBy: sum
		sourceColumn: Fiscal Month Of Fiscal Year

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fiscal Month Of Fiscal Half'
		dataType: double
		lineageTag: fc01c2d0-2813-4b93-90aa-16839b6d138e
		summarizeBy: sum
		sourceColumn: Fiscal Month Of Fiscal Half

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fiscal Month End Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 35dea510-9a54-46d7-8a61-7f5f44a9b1c8
		summarizeBy: none
		sourceColumn: Fiscal Month End Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fiscal Quarter Of Fiscal Year'
		dataType: double
		lineageTag: 18caaa53-c07e-4471-b0b3-bbcda19badc8
		summarizeBy: sum
		sourceColumn: Fiscal Quarter Of Fiscal Year

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fiscal Quarter Time Span'
		dataType: double
		lineageTag: a41918f0-c621-4cb7-840c-467965c81389
		summarizeBy: sum
		sourceColumn: Fiscal Quarter Time Span

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fiscal Quarter Start Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: bf9a6340-ef57-4cb3-99cf-29a725ea0498
		summarizeBy: none
		sourceColumn: Fiscal Quarter Start Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fiscal Quarter Name'
		dataType: string
		lineageTag: 28ce9330-d559-4be4-965b-a9d697b304c5
		summarizeBy: none
		sourceColumn: Fiscal Quarter Name

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Quarter Of Fiscal Half'
		dataType: double
		lineageTag: 6554f579-946d-4f4d-9057-931af2924522
		summarizeBy: sum
		sourceColumn: Fiscal Quarter Of Fiscal Half

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fiscal Quarter End Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 18df468f-3c9d-4f84-b331-852d8cf3ac68
		summarizeBy: none
		sourceColumn: Fiscal Quarter End Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fiscal Half Start Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 56690903-5176-43cb-810b-0f0b72cb814e
		summarizeBy: none
		sourceColumn: Fiscal Half Start Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fiscal Half Time Span'
		dataType: double
		lineageTag: 02193648-d2b4-4829-9fde-39a3e6c0fd44
		summarizeBy: sum
		sourceColumn: Fiscal Half Time Span

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fiscal Half Of Fiscal Year'
		dataType: double
		lineageTag: 63ca22cc-bed2-4675-85a3-0249c0b9f43a
		summarizeBy: sum
		sourceColumn: Fiscal Half Of Fiscal Year

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fiscal Half Name'
		dataType: string
		lineageTag: 2fca5516-8ec7-466c-91e4-1abce981d872
		summarizeBy: none
		sourceColumn: Fiscal Half Name

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Half End Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: e03074e1-7162-4852-8ef5-f4078a90f073
		summarizeBy: none
		sourceColumn: Fiscal Half End Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fiscal Year End Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9a65064d-d7fa-45eb-bf9f-30b406ec17f0
		summarizeBy: none
		sourceColumn: Fiscal Year End Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fiscal Year Start Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 611d216a-9e54-4765-aeb5-502263be4658
		summarizeBy: none
		sourceColumn: Fiscal Year Start Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fiscal Year Name'
		dataType: string
		lineageTag: 72753d82-eee4-4471-8da5-1dc86a18e2b5
		summarizeBy: none
		sourceColumn: Fiscal Year Name

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Year Time Span'
		dataType: double
		lineageTag: 8fe67626-c539-4f5d-9a88-61cc2197ed33
		summarizeBy: sum
		sourceColumn: Fiscal Year Time Span

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Ly Day'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 11b0295e-159c-4740-a90c-3a00f7be62d0
		summarizeBy: none
		sourceColumn: Ly Day

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ly Week Start Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5203753a-72e5-43ec-a66a-72e3ad230227
		summarizeBy: none
		sourceColumn: Ly Week Start Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ly Week End Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 90fca4b3-97b5-4ef3-90e9-df5f0ac24cfd
		summarizeBy: none
		sourceColumn: Ly Week End Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ly Month Start Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6539c25b-6621-4716-bd4d-7b39fa20d97c
		summarizeBy: none
		sourceColumn: Ly Month Start Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ly Month End Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: b7f8ad8d-a5b0-478e-9648-24f7924906e9
		summarizeBy: none
		sourceColumn: Ly Month End Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ly Quarter Start Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5c7f5baa-99c8-49f7-bd6c-262fcbfcd0fb
		summarizeBy: none
		sourceColumn: Ly Quarter Start Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ly Quarter End Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 59e8234a-6f80-418f-9e63-213c6a160d6f
		summarizeBy: none
		sourceColumn: Ly Quarter End Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ly Year Start Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9ed37d3b-6136-4a86-92ba-a5942e3a5ffd
		summarizeBy: none
		sourceColumn: Ly Year Start Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ly Year End Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1be62fa7-b2c2-420d-83de-f3f1306bf40e
		summarizeBy: none
		sourceColumn: Ly Year End Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Payroll Begin Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2068669a-0767-41aa-a7e7-7bb8247e8139
		summarizeBy: none
		sourceColumn: Payroll Begin Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Payroll End Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: f6a98713-fe64-41d7-82a4-a829cb5bc361
		summarizeBy: none
		sourceColumn: Payroll End Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Lly Day'
		dataType: dateTime
		formatString: Long Date
		lineageTag: b8bc380d-58a5-4643-8287-f0105dfd671a
		summarizeBy: none
		sourceColumn: Lly Day

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Lly Week Start Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7a5953b6-e938-448f-a47d-9f65c58d1936
		summarizeBy: none
		sourceColumn: Lly Week Start Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Lly Week End Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 20cd11a3-c6ae-416c-8802-17871289d59a
		summarizeBy: none
		sourceColumn: Lly Week End Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Lly Month Start Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: c36d3bc0-834d-47bf-bae0-fb7dc184f9dd
		summarizeBy: none
		sourceColumn: Lly Month Start Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Lly Month End Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2c8ffdb0-0d7a-4332-9aef-94eef8b3c599
		summarizeBy: none
		sourceColumn: Lly Month End Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Lly Quarter Start Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: e842ab0f-d6fa-47eb-9d1c-88106f6d61aa
		summarizeBy: none
		sourceColumn: Lly Quarter Start Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Lly Quarter End Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5f865da9-676a-4d89-bbf9-362ecbaac080
		summarizeBy: none
		sourceColumn: Lly Quarter End Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Lly Year Start Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: b29a5dcc-8b7c-45dd-87be-4971e5087cff
		summarizeBy: none
		sourceColumn: Lly Year Start Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Lly Year End Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 294247cd-c611-46d8-a49b-e8f81b35ca2b
		summarizeBy: none
		sourceColumn: Lly Year End Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Pnl Year Name'
		dataType: string
		lineageTag: 174cec8e-85a8-40f4-80b9-c33ac115e937
		summarizeBy: none
		sourceColumn: Pnl Year Name
		sortByColumn: 'Pnl Year Code'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Pnl Quarter Name'
		dataType: string
		lineageTag: b34efbc3-f657-4be7-8aca-5a47efba483b
		summarizeBy: none
		sourceColumn: Pnl Quarter Name
		sortByColumn: 'Pnl Quarter Code'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Pnl Period Name'
		dataType: string
		lineageTag: 045187ed-7623-4094-8d77-fd176d0705a0
		summarizeBy: none
		sourceColumn: Pnl Period Name

		annotation SummarizationSetBy = Automatic

	column 'Pnl Calendar Year Name'
		dataType: string
		lineageTag: 3a3ebae0-6bb1-4616-99d2-4fb36a638c93
		summarizeBy: none
		sourceColumn: Pnl Calendar Year Name

		annotation SummarizationSetBy = Automatic

	column 'Pnl Calendar Month Name'
		dataType: string
		lineageTag: 8d022806-3837-4f44-81cc-6adabcb05cf0
		summarizeBy: none
		sourceColumn: Pnl Calendar Month Name
		sortByColumn: 'Pnl Calendar Month Code'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Pnl Offset Year Name'
		dataType: string
		lineageTag: 1e5791f7-2fe0-4fcc-8359-e5790a67f2c6
		summarizeBy: none
		sourceColumn: Pnl Offset Year Name

		annotation SummarizationSetBy = Automatic

	column 'Pnl Offset Quarter Name'
		dataType: string
		lineageTag: cfc7cdf0-d9e3-4f00-add7-8250f859ce51
		summarizeBy: none
		sourceColumn: Pnl Offset Quarter Name

		annotation SummarizationSetBy = Automatic

	column 'Pnl Offset Period Name'
		dataType: string
		lineageTag: dc746899-5677-48a4-a193-45d5d1638863
		summarizeBy: none
		sourceColumn: Pnl Offset Period Name

		annotation SummarizationSetBy = Automatic

	column 'Pnl Calendar Offset Year Name'
		dataType: string
		lineageTag: 49808653-e4b5-4ffd-b30e-0f2d6febef92
		summarizeBy: none
		sourceColumn: Pnl Calendar Offset Year Name

		annotation SummarizationSetBy = Automatic

	column 'Pnl Calendar Offset Month Name'
		dataType: string
		lineageTag: 4552ac09-63f7-4ab9-8fd8-a4c916b26bd5
		summarizeBy: none
		sourceColumn: Pnl Calendar Offset Month Name

		annotation SummarizationSetBy = Automatic

	column 'Pnl Ly Day'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 34d3c37d-72a7-4ab4-bfdd-d32668d7aee3
		summarizeBy: none
		sourceColumn: Pnl Ly Day

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Pnl Ly Year Start Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 326135fb-2f3f-4fd3-9ffa-50365afb0bcb
		summarizeBy: none
		sourceColumn: Pnl Ly Year Start Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Pnl Ly Year End Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: ea2a71d9-7f06-4885-84e6-bce5d774639f
		summarizeBy: none
		sourceColumn: Pnl Ly Year End Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Pnl Ly Month Start Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: f77f2a90-d126-4a5f-b90e-62398dac460a
		summarizeBy: none
		sourceColumn: Pnl Ly Month Start Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Pnl Ly Month End Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 675e7c37-0c7c-4810-97ca-e358749d0c5e
		summarizeBy: none
		sourceColumn: Pnl Ly Month End Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Pnl Ly Week Start Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: d1422302-420d-417a-89ed-76cf5c95dc1d
		summarizeBy: none
		sourceColumn: Pnl Ly Week Start Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Pnl Ly Week End Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: f0e12833-aabf-4544-9bb7-0d71d4f02bc9
		summarizeBy: none
		sourceColumn: Pnl Ly Week End Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Pnl Ly Quarter Start Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 24cada99-b968-49a8-9171-7f15ead02f60
		summarizeBy: none
		sourceColumn: Pnl Ly Quarter Start Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Pnl Ly Quarter End Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4658ed2f-05d3-4a16-9d22-19a59287a405
		summarizeBy: none
		sourceColumn: Pnl Ly Quarter End Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Pnl Lly Day'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9b013bf4-10ea-48a0-91a6-c12e06d36945
		summarizeBy: none
		sourceColumn: Pnl Lly Day

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Pnl Lly Year Start Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8950ec2e-a3e5-4fb2-bf69-5bb3c8b937a6
		summarizeBy: none
		sourceColumn: Pnl Lly Year Start Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Pnl Lly Year End Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6203e445-4a65-43f6-87dc-c4ee7afc172e
		summarizeBy: none
		sourceColumn: Pnl Lly Year End Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Pnl Lly Month Start Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6cbd12ce-1a74-49cf-8dc9-dd97b9c87c72
		summarizeBy: none
		sourceColumn: Pnl Lly Month Start Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Pnl Lly Month End Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9baeeed1-625b-491a-935a-3065659bae65
		summarizeBy: none
		sourceColumn: Pnl Lly Month End Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Pnl Lly Week Start Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 083c701d-10ac-4a38-b877-a9188a1b7204
		summarizeBy: none
		sourceColumn: Pnl Lly Week Start Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Pnl Lly Week End Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 25033fe2-43aa-4b19-b11e-1464de7ec9f3
		summarizeBy: none
		sourceColumn: Pnl Lly Week End Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Pnl Lly Quarter Start Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: b67556e5-ffb6-4bd5-8f73-17f4b4ebb60f
		summarizeBy: none
		sourceColumn: Pnl Lly Quarter Start Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Pnl Lly Quarter End Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 04ae2117-c6d2-4a78-a585-113327012ba7
		summarizeBy: none
		sourceColumn: Pnl Lly Quarter End Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Pnl Payroll Begin Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: d516ab91-c81a-4ba1-94bc-4e7b113f9175
		summarizeBy: none
		sourceColumn: Pnl Payroll Begin Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Pnl Payroll End Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 57434b00-45a7-44af-ba26-3b1ce2e8cc16
		summarizeBy: none
		sourceColumn: Pnl Payroll End Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Pnl Payroll Pay Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 45c18165-92f1-4ee3-b9f7-01959790efd0
		summarizeBy: none
		sourceColumn: Pnl Payroll Pay Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Is Yesterday'
		dataType: double
		lineageTag: 52d03280-8c31-482b-a8ef-4a37f710197f
		summarizeBy: sum
		sourceColumn: Is Yesterday

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Is Wtd'
		dataType: double
		lineageTag: 27d4dbe5-8a6f-4a73-86ed-68e8bb29b969
		summarizeBy: sum
		sourceColumn: Is Wtd

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Is Mtd'
		dataType: double
		lineageTag: 2d4204f0-5876-4603-b557-aef0dcba887a
		summarizeBy: sum
		sourceColumn: Is Mtd

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Is Ytd'
		dataType: double
		lineageTag: efefaa27-2572-446e-82c5-ab5b380b7984
		summarizeBy: sum
		sourceColumn: Is Ytd

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Is Rolling 7'
		dataType: double
		lineageTag: 0be1c73b-6b54-4f60-affc-043ed84d1b94
		summarizeBy: sum
		sourceColumn: Is Rolling 7

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Is Rolling 28'
		dataType: double
		lineageTag: 69872ea5-3075-4cd6-8245-0b18e5ee9362
		summarizeBy: sum
		sourceColumn: Is Rolling 28

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Is Pnl Mth'
		dataType: double
		lineageTag: 0630522f-fb98-4e04-b2ad-7fdc903d0386
		summarizeBy: sum
		sourceColumn: Is Pnl Mth

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Is Pnl Year'
		dataType: double
		lineageTag: 452c26ea-6c66-44cc-8414-a25d7b97072f
		summarizeBy: sum
		sourceColumn: Is Pnl Year

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Day Of Pnl Year'
		dataType: double
		lineageTag: b2d97f48-c81e-4c09-ad6c-f27d852baa5b
		summarizeBy: sum
		sourceColumn: Day Of Pnl Year

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Day Of Pnl Half'
		dataType: double
		lineageTag: edafc394-38ef-4c56-81b2-ebeff526ffa2
		summarizeBy: sum
		sourceColumn: Day Of Pnl Half

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Day Of Pnl Quarter'
		dataType: double
		lineageTag: 4b9e955b-4ec5-4047-87c7-0536c1cdea98
		summarizeBy: sum
		sourceColumn: Day Of Pnl Quarter

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Week Of Pnl Year'
		dataType: double
		lineageTag: cf6d6c3b-5841-4f05-8af2-e5d05ab8e68a
		summarizeBy: sum
		sourceColumn: Week Of Pnl Year

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Pnl Week Name'
		dataType: string
		lineageTag: f87b68aa-296f-4849-b0b8-554144fe63ed
		summarizeBy: none
		sourceColumn: Pnl Week Name

		annotation SummarizationSetBy = Automatic

	partition Date = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"381214d4-ea63-4a86-87da-8aebf81978ae" = Workspaces{[workspaceId="381214d4-ea63-4a86-87da-8aebf81978ae"]}[Data],
				    #"c8f09baa-dbd9-401b-8d55-1801f53ef645" = #"381214d4-ea63-4a86-87da-8aebf81978ae"{[dataflowId="c8f09baa-dbd9-401b-8d55-1801f53ef645"]}[Data],
				    Date_ = #"c8f09baa-dbd9-401b-8d55-1801f53ef645"{[entity="Date",version=""]}[Data],
				    #"Merged Queries" = Table.NestedJoin(Date_, {"DATE_KEY"}, #"Sales and Return Errors", {"Written Sales Date"}, "Sales and Return Errors", JoinKind.Inner),
				    #"Removed Other Columns" = Table.SelectColumns(#"Merged Queries",{"DATE_KEY", "Fiscal Week Code", "Fiscal Month Code", "Fiscal Quarter Code", "Fiscal Half Code", "Fiscal Year Code", "Pnl Year Code", "Pnl Quarter Code", "Pnl Period Code", "Pnl Calendar Year Code", "Pnl Calendar Month Code", "Day Of Fiscal Week", "Day Of Fiscal Month", "Day Of Fiscal Quarter", "Day Of Fiscal Half", "Day Of Fiscal Year", "Fiscal Week Of Fiscal Year", "Fiscal Week Start Date", "Fiscal Week Of Fiscal Quarter", "Fiscal Week Of Fiscal Half", "Fiscal Week End Date", "Fiscal Week Name", "Fiscal Week Of Fiscal Month", "Fiscal Month Start Date", "Fiscal Month Name", "Fiscal Month Time Span", "Fiscal Month Of Fiscal Quarter", "Fiscal Month Of Fiscal Year", "Fiscal Month Of Fiscal Half", "Fiscal Month End Date", "Fiscal Quarter Of Fiscal Year", "Fiscal Quarter Time Span", "Fiscal Quarter Start Date", "Fiscal Quarter Name", "Fiscal Quarter Of Fiscal Half", "Fiscal Quarter End Date", "Fiscal Half Start Date", "Fiscal Half Time Span", "Fiscal Half Of Fiscal Year", "Fiscal Half Name", "Fiscal Half End Date", "Fiscal Year End Date", "Fiscal Year Start Date", "Fiscal Year Name", "Fiscal Year Time Span", "Ly Day", "Ly Week Start Date", "Ly Week End Date", "Ly Month Start Date", "Ly Month End Date", "Ly Quarter Start Date", "Ly Quarter End Date", "Ly Year Start Date", "Ly Year End Date", "Payroll Begin Date", "Payroll End Date", "Lly Day", "Lly Week Start Date", "Lly Week End Date", "Lly Month Start Date", "Lly Month End Date", "Lly Quarter Start Date", "Lly Quarter End Date", "Lly Year Start Date", "Lly Year End Date", "Pnl Year Name", "Pnl Quarter Name", "Pnl Period Name", "Pnl Calendar Year Name", "Pnl Calendar Month Name", "Pnl Offset Year Name", "Pnl Offset Quarter Name", "Pnl Offset Period Name", "Pnl Calendar Offset Year Name", "Pnl Calendar Offset Month Name", "Pnl Ly Day", "Pnl Ly Year Start Date", "Pnl Ly Year End Date", "Pnl Ly Month Start Date", "Pnl Ly Month End Date", "Pnl Ly Week Start Date", "Pnl Ly Week End Date", "Pnl Ly Quarter Start Date", "Pnl Ly Quarter End Date", "Pnl Lly Day", "Pnl Lly Year Start Date", "Pnl Lly Year End Date", "Pnl Lly Month Start Date", "Pnl Lly Month End Date", "Pnl Lly Week Start Date", "Pnl Lly Week End Date", "Pnl Lly Quarter Start Date", "Pnl Lly Quarter End Date", "Pnl Payroll Begin Date", "Pnl Payroll End Date", "Pnl Payroll Pay Date", "Is Yesterday", "Is Wtd", "Is Mtd", "Is Ytd", "Is Rolling 7", "Is Rolling 28", "Is Pnl Mth", "Is Pnl Year", "Day Of Pnl Year", "Day Of Pnl Half", "Day Of Pnl Quarter", "Week Of Pnl Year", "Pnl Week Name"})
				in
				    #"Removed Other Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

