table 'Date Group'
	lineageTag: 7c215d9d-6386-4809-bb96-2c76fe755487

	column DATE_KEY
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 3999bfe2-29e1-4f36-bff8-e6a90459ccf2
		summarizeBy: none
		sourceColumn: DATE_KEY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Date Group Code'
		dataType: string
		lineageTag: 1349920a-2530-41ee-a4e8-9cb63b58da13
		summarizeBy: none
		sourceColumn: Date Group Code

		annotation SummarizationSetBy = Automatic

	column 'Date Group Desc'
		dataType: string
		lineageTag: 98e3c9c8-0b55-4b8e-886b-113171742a6d
		summarizeBy: none
		sourceColumn: Date Group Desc
		sortByColumn: 'Date Group Sort Order'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Date Group Sort Order'
		dataType: double
		lineageTag: fc94573f-a006-490b-a99f-d4a3e81820a7
		summarizeBy: sum
		sourceColumn: Date Group Sort Order

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Date Group Value'
		dataType: string
		lineageTag: 001b9a7a-0a37-4512-8668-44f3a8db04b2
		summarizeBy: none
		sourceColumn: Date Group Value

		annotation SummarizationSetBy = Automatic

	column 'Date Group Value Order'
		dataType: double
		lineageTag: 87183f4b-01c7-4e06-93e7-feb37a5a9551
		summarizeBy: sum
		sourceColumn: Date Group Value Order

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Date Group' = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"381214d4-ea63-4a86-87da-8aebf81978ae" = Workspaces{[workspaceId="381214d4-ea63-4a86-87da-8aebf81978ae"]}[Data],
				    #"c8f09baa-dbd9-401b-8d55-1801f53ef645" = #"381214d4-ea63-4a86-87da-8aebf81978ae"{[dataflowId="c8f09baa-dbd9-401b-8d55-1801f53ef645"]}[Data],
				    #"Date Group_" = #"c8f09baa-dbd9-401b-8d55-1801f53ef645"{[entity="Date Group",version=""]}[Data],
				    #"Filtered Rows" = Table.SelectRows(#"Date Group_", each (List.Contains({"TDA", "DAY", "WTD", "MTD", "QTD", "YTD", "R07", "R14", "R21", "R28", "WEC", "MEC", "R52W", "CWK", "PWK", "TCM", "TPM", "MR1", "EVD", "EVD", "EVD", "EVD", "WDL", "MDL", "R03M", "R06M", "R12M", "R42D", "L7M", "CFW", "CFM", "CFQ", "CFY", "CPNL", "R13W", "R26W", "TCY", "PQT", "L07D", "L14D", "L28D", "L30D", "L60D", "L90D", "L12M"}, [Date Group Code]) = true)),
				    #"Merged Queries" = Table.NestedJoin(#"Filtered Rows", {"DATE_KEY"}, Date, {"DATE_KEY"}, "Date", JoinKind.Inner),
				    #"Removed Other Columns" = Table.SelectColumns(#"Merged Queries",{"DATE_KEY", "Date Group Code", "Date Group Desc", "Date Group Sort Order", "Date Group Value", "Date Group Value Order"})
				in
				    #"Removed Other Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

