table 'EC Products'
	lineageTag: 24dfb6c2-e13b-4eac-9782-97dd9098b767

	column COUNTRY_ID
		dataType: double
		lineageTag: cac837e2-559d-47a5-a94a-a4c409c4197e
		summarizeBy: none
		sourceColumn: COUNTRY_ID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PRODUCT_GROUP_ID
		dataType: double
		lineageTag: 7e7cc971-7f40-4eb8-b227-c444f74b9722
		summarizeBy: none
		sourceColumn: PRODUCT_GROUP_ID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DEPARTMENT_ID
		dataType: double
		lineageTag: c84482dc-000e-4f0a-90d6-0a3e3594490a
		summarizeBy: none
		sourceColumn: DEPARTMENT_ID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column COUNTRY_STOCK_CODE
		dataType: string
		isHidden
		lineageTag: cbe40831-d40b-4dc3-8767-0c6c169fc53e
		summarizeBy: none
		sourceColumn: COUNTRY_STOCK_CODE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column STOCK_CODE
		dataType: string
		lineageTag: 9e0810bf-315b-4119-830d-eb1541878632
		summarizeBy: none
		sourceColumn: STOCK_CODE

		annotation SummarizationSetBy = Automatic

	column 'Season Code'
		dataType: string
		lineageTag: 0ec01493-c313-4efd-a0e6-24a4ce46243c
		summarizeBy: none
		sourceColumn: Season Code

		annotation SummarizationSetBy = Automatic

	column 'Model Number'
		dataType: string
		lineageTag: 43770bdc-7dd7-4a9a-83dc-beeeb37848db
		summarizeBy: none
		sourceColumn: Model Number

		annotation SummarizationSetBy = Automatic

	column 'Product Description'
		dataType: string
		lineageTag: 7914a7e9-b2cd-4bbe-a18f-4cd83b3ab430
		summarizeBy: none
		sourceColumn: Product Description

		annotation SummarizationSetBy = Automatic

	column 'Product Description Extended'
		dataType: string
		lineageTag: 878029e6-3ab6-458c-b0dd-f663a289a25d
		summarizeBy: none
		sourceColumn: Product Description Extended

		annotation SummarizationSetBy = Automatic

	column 'Supplier Product Description'
		dataType: string
		lineageTag: bd4b474e-0ae7-43c7-9e48-08fd77ebb7c1
		summarizeBy: none
		sourceColumn: Supplier Product Description

		annotation SummarizationSetBy = Automatic

	column Brand
		dataType: string
		lineageTag: f3243776-7fe0-4df9-b667-9dd0e22f74e3
		summarizeBy: none
		sourceColumn: Brand

		annotation SummarizationSetBy = Automatic

	column 'Pack Width'
		dataType: double
		lineageTag: 5ca5bc69-deb6-46a6-bd4b-e764cd8d02ed
		summarizeBy: none
		sourceColumn: Pack Width

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Pack Height'
		dataType: double
		lineageTag: adb46776-788f-449c-8443-1c4eabfe2d09
		summarizeBy: none
		sourceColumn: Pack Height

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Pack Length'
		dataType: double
		lineageTag: f50c40ae-303f-44eb-a871-6e5c53252863
		summarizeBy: none
		sourceColumn: Pack Length

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Packed Volume'
		dataType: double
		lineageTag: 6b3c5081-6a95-404f-927a-2882a9850246
		summarizeBy: none
		sourceColumn: Packed Volume

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Supplier Name'
		dataType: string
		lineageTag: e8be47ea-b2a1-4e3d-9ffc-5e5629b0ca42
		summarizeBy: none
		sourceColumn: Supplier Name

		annotation SummarizationSetBy = Automatic

	column 'Supplier Inactive Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: b48b1b6c-6c67-4758-a655-ff742b29807c
		summarizeBy: none
		sourceColumn: Supplier Inactive Date

		annotation SummarizationSetBy = Automatic

	column 'Supplier Inactive'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 766cf085-b29a-4bda-b2f8-4ec09783b08c
		summarizeBy: none
		sourceColumn: Supplier Inactive

		annotation SummarizationSetBy = Automatic

	column 'Product Group Desc'
		dataType: string
		lineageTag: 9b35f712-782f-4215-bca1-99ff2dc514f6
		summarizeBy: none
		sourceColumn: Product Group Desc

		annotation SummarizationSetBy = Automatic

	column 'Department Desc'
		dataType: string
		lineageTag: b95ddd0c-1340-4cd1-8278-b6c3d8553539
		summarizeBy: none
		sourceColumn: Department Desc

		annotation SummarizationSetBy = Automatic

	partition 'EC Products' = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"381214d4-ea63-4a86-87da-8aebf81978ae" = Workspaces{[workspaceId="381214d4-ea63-4a86-87da-8aebf81978ae"]}[Data],
				    #"c8f09baa-dbd9-401b-8d55-1801f53ef645" = #"381214d4-ea63-4a86-87da-8aebf81978ae"{[dataflowId="c8f09baa-dbd9-401b-8d55-1801f53ef645"]}[Data],
				    Product_ = #"c8f09baa-dbd9-401b-8d55-1801f53ef645"{[entity="Product",version=""]}[Data],
				    #"Filtered Rows" = Table.SelectRows(Product_, each ([COUNTRY_ID] = COUNTRY_ID)),
				    #"Merged Queries" = Table.NestedJoin(#"Filtered Rows", {"COUNTRY_STOCK_CODE"}, #"Sales and Return Errors", {"COUNTRY_EXTRA_CARE_STOCK_CODE"}, "Sales and Return Errors", JoinKind.Inner),
				    #"Removed Other Columns" = Table.SelectColumns(#"Merged Queries",{"COUNTRY_ID", "PRODUCT_GROUP_ID", "DEPARTMENT_ID", "COUNTRY_STOCK_CODE", "STOCK_CODE", "Season Code", "Model Number", "Product Description", "Product Description Extended", "Supplier Product Description", "Brand", "Pack Width", "Pack Height", "Pack Length", "Packed Volume", "Supplier Name", "Supplier Inactive Date", "Supplier Inactive", "Product Group Desc", "Department Desc"})
				in
				    #"Removed Other Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

