table 'Extra Care Salesperson'
	lineageTag: 1ad0e432-28ba-4e8b-ba66-ddf223d9a279

	column STORE_ID
		dataType: double
		lineageTag: 5ab4ed9a-cb65-4101-8f00-893c07befff1
		summarizeBy: count
		sourceColumn: STORE_ID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column COUNTRY_ID
		dataType: double
		lineageTag: 1dcea5a5-e579-44b0-96e0-d3fb683d9476
		summarizeBy: count
		sourceColumn: COUNTRY_ID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column COUNTRY_EMPLOYEE_CODE
		dataType: string
		isHidden
		lineageTag: dbb88712-5bd5-4e9f-becb-10dfe6b9a5d5
		summarizeBy: none
		sourceColumn: COUNTRY_EMPLOYEE_CODE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EMPLOYEE_CODE
		dataType: string
		lineageTag: 63fccdce-11bd-428c-bcb3-fd183cac205d
		summarizeBy: none
		sourceColumn: EMPLOYEE_CODE

		annotation SummarizationSetBy = Automatic

	column 'Employee Store'
		dataType: string
		lineageTag: dcbbd1be-b2c2-4007-a76a-b0b9305a01cf
		summarizeBy: none
		sourceColumn: Employee Store

		annotation SummarizationSetBy = Automatic

	column 'Employee Type'
		dataType: string
		lineageTag: 421383e5-d490-4489-ac72-fb13db726f72
		summarizeBy: none
		sourceColumn: Employee Type

		annotation SummarizationSetBy = Automatic

	column 'Employee Position Desc'
		dataType: string
		lineageTag: 7bcafe53-aeb2-4ae1-9f7b-d36768d50b1b
		summarizeBy: none
		sourceColumn: Employee Position Desc

		annotation SummarizationSetBy = Automatic

	column 'Employee Start Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: a3c20dbf-664d-4b15-845a-cf9febf2c6f4
		summarizeBy: none
		sourceColumn: Employee Start Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Employee Termination Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 348b6d2a-062c-45aa-b0b9-52d9644a60ac
		summarizeBy: none
		sourceColumn: Employee Termination Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Employee Status'
		dataType: string
		lineageTag: 6ccf5dfa-7bbd-4223-96e6-cf71a04d2fd0
		summarizeBy: none
		sourceColumn: Employee Status

		annotation SummarizationSetBy = Automatic

	column 'Employee Full Name'
		dataType: string
		lineageTag: 5fd38e51-35f7-4048-b751-49fc44a2ca01
		summarizeBy: none
		sourceColumn: Employee Full Name

		annotation SummarizationSetBy = Automatic

	column 'Employee Tenure'
		dataType: double
		lineageTag: 25818bc6-3ec4-4393-83ef-381f8d55a935
		summarizeBy: sum
		sourceColumn: Employee Tenure

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Employee Work Email'
		dataType: string
		lineageTag: 455ee1d3-bdf5-4304-9aa3-db9e94366e9f
		summarizeBy: none
		sourceColumn: Employee Work Email

		annotation SummarizationSetBy = Automatic

	partition 'Extra Care Salesperson' = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"381214d4-ea63-4a86-87da-8aebf81978ae" = Workspaces{[workspaceId="381214d4-ea63-4a86-87da-8aebf81978ae"]}[Data],
				    #"c8f09baa-dbd9-401b-8d55-1801f53ef645" = #"381214d4-ea63-4a86-87da-8aebf81978ae"{[dataflowId="c8f09baa-dbd9-401b-8d55-1801f53ef645"]}[Data],
				    Employee_ = #"c8f09baa-dbd9-401b-8d55-1801f53ef645"{[entity="Employee",version=""]}[Data],
				    #"Filtered Rows" = Table.SelectRows(Employee_, each ([COUNTRY_ID] = COUNTRY_ID)),
				    #"Merged Queries" = Table.NestedJoin(#"Filtered Rows", {"COUNTRY_EMPLOYEE_CODE"}, #"Sales and Return Errors", {"COUNTRY_EXTRA_CARE_EMPLOYEE_CODE"}, "Sales and Return Errors", JoinKind.Inner),
				    #"Removed Other Columns" = Table.SelectColumns(#"Merged Queries",{"STORE_ID", "COUNTRY_ID", "COUNTRY_EMPLOYEE_CODE", "EMPLOYEE_CODE", "Employee Store", "Employee Type", "Employee Position Desc", "Employee Start Date", "Employee Termination Date", "Employee Status", "Employee Full Name", "Employee Tenure", "Employee Work Email"})
				in
				    #"Removed Other Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

