table 'Primary Products'
	lineageTag: 88173605-3372-4f05-84de-c8edb9b59c11

	column COUNTRY_ID
		dataType: double
		isHidden
		lineageTag: 59ac2f99-4a86-4d18-aaaa-72f54e9e0f61
		summarizeBy: none
		sourceColumn: COUNTRY_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PRODUCT_GROUP_ID
		dataType: double
		lineageTag: 8dc2eca7-e86a-457e-a104-f0be5478b496
		summarizeBy: none
		sourceColumn: PRODUCT_GROUP_ID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DEPARTMENT_ID
		dataType: double
		lineageTag: b1195a6b-b28b-4b10-bb5d-6fd15e133672
		summarizeBy: none
		sourceColumn: DEPARTMENT_ID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column COUNTRY_STOCK_CODE
		dataType: string
		isHidden
		lineageTag: 7b3a2a3e-bed7-4201-a50a-98f46370bc3c
		summarizeBy: none
		sourceColumn: COUNTRY_STOCK_CODE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column STOCK_CODE
		dataType: string
		lineageTag: 51e94226-53c5-4c21-8ea3-a8fe1fd9fbf2
		summarizeBy: none
		sourceColumn: STOCK_CODE

		annotation SummarizationSetBy = Automatic

	column 'Season Code'
		dataType: string
		lineageTag: df4b180b-f6b2-4385-a522-2770397ea668
		summarizeBy: none
		sourceColumn: Season Code

		annotation SummarizationSetBy = Automatic

	column 'Model Number'
		dataType: string
		lineageTag: aa00896b-62e1-4c6c-9948-a23fcd755da1
		summarizeBy: none
		sourceColumn: Model Number

		annotation SummarizationSetBy = Automatic

	column 'Product Description'
		dataType: string
		lineageTag: a97578c1-75ce-48e2-ba8d-33c3fc0a9a4c
		summarizeBy: none
		sourceColumn: Product Description

		annotation SummarizationSetBy = Automatic

	column 'Product Description Extended'
		dataType: string
		lineageTag: 52d4991f-d17d-4dbb-86b2-263dcb651369
		summarizeBy: none
		sourceColumn: Product Description Extended

		annotation SummarizationSetBy = Automatic

	column 'Supplier Product Description'
		dataType: string
		lineageTag: 5717e773-2077-4739-b0fb-5d51c973eef3
		summarizeBy: none
		sourceColumn: Supplier Product Description

		annotation SummarizationSetBy = Automatic

	column Brand
		dataType: string
		lineageTag: be9a8dd4-b004-480c-a486-f136341baabe
		summarizeBy: none
		sourceColumn: Brand

		annotation SummarizationSetBy = Automatic

	column 'Pack Width'
		dataType: double
		lineageTag: a3e0ac3c-0ec9-482d-936d-0bb395288c0f
		summarizeBy: none
		sourceColumn: Pack Width

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Pack Height'
		dataType: double
		lineageTag: 312ca5de-4e32-4ee0-a571-5d358f43838c
		summarizeBy: none
		sourceColumn: Pack Height

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Pack Length'
		dataType: double
		lineageTag: 68bb82ea-3e9a-403e-92bd-90dc54e5d2f0
		summarizeBy: none
		sourceColumn: Pack Length

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Packed Volume'
		dataType: double
		lineageTag: e33aed65-5001-49a8-afbd-4a55201ae030
		summarizeBy: none
		sourceColumn: Packed Volume

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Supplier Name'
		dataType: string
		lineageTag: cd323d4f-e26a-4757-8eb7-ae4f49e2d969
		summarizeBy: none
		sourceColumn: Supplier Name

		annotation SummarizationSetBy = Automatic

	column 'Supplier Inactive Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 6fe70103-d408-4514-9e53-08787c4904d8
		summarizeBy: none
		sourceColumn: Supplier Inactive Date

		annotation SummarizationSetBy = Automatic

	column 'Supplier Inactive'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 7f7dc0b6-5f64-4576-8165-4dabe91e2f5b
		summarizeBy: none
		sourceColumn: Supplier Inactive

		annotation SummarizationSetBy = Automatic

	column 'Product Group Desc'
		dataType: string
		lineageTag: df0012b7-0dfa-4a98-842e-aff4b542c4db
		summarizeBy: none
		sourceColumn: Product Group Desc

		annotation SummarizationSetBy = Automatic

	column 'Department Desc'
		dataType: string
		lineageTag: 710ad8bb-8b44-403c-bd03-66bb4c606603
		summarizeBy: none
		sourceColumn: Department Desc

		annotation SummarizationSetBy = Automatic

	partition 'Primary Products' = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"381214d4-ea63-4a86-87da-8aebf81978ae" = Workspaces{[workspaceId="381214d4-ea63-4a86-87da-8aebf81978ae"]}[Data],
				    #"c8f09baa-dbd9-401b-8d55-1801f53ef645" = #"381214d4-ea63-4a86-87da-8aebf81978ae"{[dataflowId="c8f09baa-dbd9-401b-8d55-1801f53ef645"]}[Data],
				    Product_ = #"c8f09baa-dbd9-401b-8d55-1801f53ef645"{[entity="Product",version=""]}[Data],
				    #"Filtered Rows" = Table.SelectRows(Product_, each ([COUNTRY_ID] = COUNTRY_ID)),
				    #"Merged Queries" = Table.NestedJoin(#"Filtered Rows", {"COUNTRY_STOCK_CODE"}, #"Sales and Return Errors", {"COUNTRY_PRIMARY_STOCK_CODE"}, "Sales and Return Errors", JoinKind.Inner),
				    #"Removed Other Columns" = Table.SelectColumns(#"Merged Queries",{"COUNTRY_ID", "PRODUCT_GROUP_ID", "DEPARTMENT_ID", "COUNTRY_STOCK_CODE", "STOCK_CODE", "Season Code", "Model Number", "Product Description", "Product Description Extended", "Supplier Product Description", "Brand", "Pack Width", "Pack Height", "Pack Length", "Packed Volume", "Supplier Name", "Supplier Inactive Date", "Supplier Inactive", "Product Group Desc", "Department Desc"})
				in
				    #"Removed Other Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

