table 'Sales and Return Errors'
	lineageTag: f7539c61-d379-4eff-ae65-0589b9537a07

	column 'Written Reference'
		dataType: string
		lineageTag: caa95435-cb11-46d9-8874-c298f38f4eeb
		summarizeBy: distinctCount
		sourceColumn: Written Reference

		annotation SummarizationSetBy = User

	column 'Order Line Item'
		dataType: string
		lineageTag: 747c6de0-48d0-4525-8de8-24db6528b797
		summarizeBy: none
		sourceColumn: Order Line Item

		annotation SummarizationSetBy = Automatic

	column 'Reversed Transaction'
		dataType: string
		lineageTag: 0b3bb91e-519c-4de0-bbec-760bd6fb2343
		summarizeBy: none
		sourceColumn: Reversed Transaction

		annotation SummarizationSetBy = Automatic

	column 'Primary Quantity'
		dataType: double
		lineageTag: 895d96b2-9fae-4fc2-8b66-4d2d8019b75b
		summarizeBy: sum
		sourceColumn: Primary Quantity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Primary Sale Price'
		dataType: double
		lineageTag: 378eb2cd-b34b-418c-b5f0-6a0435659f31
		summarizeBy: sum
		sourceColumn: Primary Sale Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Primary Sale Amount Inc Gst'
		dataType: double
		lineageTag: a4823f81-32c0-424f-bf8d-9774a50531f8
		summarizeBy: sum
		sourceColumn: Primary Sale Amount Inc Gst

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Extra Care Quantity'
		dataType: double
		lineageTag: 7c702b86-61f5-4aa1-9071-17f29467bcec
		summarizeBy: sum
		sourceColumn: Extra Care Quantity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Extra Care Sale Price'
		dataType: double
		lineageTag: 307c01c4-6f12-4666-861b-51dd793e45d9
		summarizeBy: sum
		sourceColumn: Extra Care Sale Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Error Ineligible From Manufacturers Warranty'
		dataType: double
		lineageTag: 4f1a3cda-02df-4371-baee-cc5004951a2e
		summarizeBy: sum
		sourceColumn: Error Ineligible From Manufacturers Warranty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column COUNTRY_PRIMARY_STOCK_CODE
		dataType: string
		lineageTag: ebcf39ca-65bf-4277-9dd1-050b90490b7a
		summarizeBy: none
		sourceColumn: COUNTRY_PRIMARY_STOCK_CODE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column COUNTRY_EXTRA_CARE_EMPLOYEE_CODE
		dataType: string
		lineageTag: d2f0143f-8131-408f-bf04-827b923b1859
		summarizeBy: none
		sourceColumn: COUNTRY_EXTRA_CARE_EMPLOYEE_CODE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column COUNTRY_EXTRA_CARE_STOCK_CODE
		dataType: string
		isHidden
		lineageTag: d9e1e111-2340-430e-b8d1-e064b8a35e2b
		summarizeBy: none
		sourceColumn: COUNTRY_EXTRA_CARE_STOCK_CODE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ERROR_INCORRECT_EXTRA_CARE_STOCK_CODE
		dataType: double
		lineageTag: c8c9874a-b3a5-4503-b9d1-c6ebfc866981
		summarizeBy: sum
		sourceColumn: ERROR_INCORRECT_EXTRA_CARE_STOCK_CODE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ERROR_EXCLUDED_PRIMARY_STOCK_CODE
		dataType: int64
		lineageTag: a7282900-4c2a-4a7f-b693-b3940c23c258
		summarizeBy: sum
		sourceColumn: ERROR_EXCLUDED_PRIMARY_STOCK_CODE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Discrepancy - Summarised' = ```
			
			
			VAR _WarrantyIneligibility = 
			    IF('Sales and Return Errors'[Error Ineligible From Manufacturers Warranty] = 1, 
			        "Ineligible Manufacturers Warranty", BLANK())
			
			VAR _WrongEC = 
			    IF('Sales and Return Errors'[ERROR_INCORRECT_EXTRA_CARE_STOCK_CODE] = 1, 
			        "Wrong EC SKU Sold", BLANK())
			
			VAR _NoServiceOrderCreated = 
			    IF('Sales and Return Errors'[Not Sold On Pda] = 1, 
			        "JBEC Not Sold on a PDA", BLANK())
			
			VAR _OverchargedEC = 
			    IF('Sales and Return Errors'[Error Overcharged Extra Care Pricing] = 1, 
			        "Incorrectly Charged for EC", BLANK())
			
			VAR _ManualRefund = 
			    IF('Sales and Return Errors'[Error Manual Refund] = 1, 
			        "Manual Refunds", BLANK())
			/*
			VAR _ExcludedReceipts = 
			    IF('Sales and Return Errors'[Error Excluded Receipt] = 1, 
			        "Excluded Receipts", BLANK())
			*/
			        VAR _ExcludedPrimaryProduct = 
			    IF('Sales and Return Errors'[ERROR_EXCLUDED_PRIMARY_STOCK_CODE] = 1, 
			        "Excluded Primary SKUs", BLANK())
			
			VAR _Discrepancy =
			    CONCATENATEX(
			        {
			            _WarrantyIneligibility,
			            _WrongEC,
			            _NoServiceOrderCreated,
			            _OverchargedEC,
			            _ManualRefund,
			            /*_ExcludedReceipts,*/
			            _ExcludedPrimaryProduct
			        },
			        [Value]
			        
			    )
			
			
			VAR _DiscrepancyCount = 
			    [Error Ineligible From Manufacturers Warranty] + 
			    [Error Overcharged Extra Care Pricing] + 
			    [Not Sold On Pda] + 
			    [ERROR_INCORRECT_EXTRA_CARE_STOCK_CODE] +
			    [Error Manual Refund] +
			    /*[Error Excluded Receipt] +*/
			    [ERROR_EXCLUDED_PRIMARY_STOCK_CODE]
			
			RETURN
			    IF(_DiscrepancyCount > 1, "Multiple", _Discrepancy)
			
			```
		lineageTag: 123c233c-e258-4890-956f-70004b87f2fe
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Total Errors Count' = ```
			[Error Ineligible From Manufacturers Warranty] + [Error Overcharged Extra Care Pricing] + [Not Sold On Pda] + [ERROR_INCORRECT_EXTRA_CARE_STOCK_CODE]  + [Error Manual Refund] + [ERROR_EXCLUDED_PRIMARY_STOCK_CODE] 
			```
		lineageTag: cd47e2d0-f389-4001-b6e1-3347da63ff79
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Listed Discrepancies' = ```
			
			
			VAR _List =
			    {
			        IF('Sales and Return Errors'[Error Ineligible From Manufacturers Warranty] = 1, 
			            "Ineligible Manufacturers Warranty", BLANK()),
			
			        IF('Sales and Return Errors'[ERROR_INCORRECT_EXTRA_CARE_STOCK_CODE] = 1, 
			            "Wrong EC SKU Sold", BLANK()),
			
			        IF('Sales and Return Errors'[Not Sold On Pda] = 1, 
			            "JBEC Not Sold on a PDA", BLANK()),
			
			        IF('Sales and Return Errors'[Error Overcharged Extra Care Pricing] = 1, 
			            "Incorrectly Charged for EC", BLANK()),
			
			        /*IF('Sales and Return Errors'[Error Excluded Receipt] = 1, 
			            "Excluded Receipts", BLANK()),*/
			        
			        IF('Sales and Return Errors'[Error Manual Refund] = 1, 
			            "Manual Refunds", BLANK()),
			
			        IF('Sales and Return Errors'[ERROR_EXCLUDED_PRIMARY_STOCK_CODE] = 1, 
			            "Excluded Primary SKUs", BLANK())
			    }
			
			RETURN
			    CONCATENATEX(
			        FILTER(_List, NOT ISBLANK([Value])),
			        [Value],
			        ", "
			    )
			
			```
		lineageTag: 1d08a7b0-2f48-46b3-b200-5687f10d8964
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column COUNTRY_PRIMARY_EMPLOYEE_CODE
		dataType: string
		lineageTag: 89d5af16-820a-4068-9077-965751cf3e17
		summarizeBy: none
		sourceColumn: COUNTRY_PRIMARY_EMPLOYEE_CODE

		annotation SummarizationSetBy = Automatic

	column 'Written Sales Date'
		dataType: dateTime
		formatString: d/mm/yyyy
		lineageTag: 3635107f-9b02-4b12-a8f3-630f5efa86c4
		summarizeBy: none
		sourceColumn: Written Sales Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Delivered Reference'
		dataType: string
		lineageTag: 4a0421b6-de52-424a-84b2-13a061ddb7f3
		summarizeBy: none
		sourceColumn: Delivered Reference

		annotation SummarizationSetBy = Automatic

	column 'Extra Care Status'
		dataType: string
		lineageTag: 1d4de33c-a369-4123-af88-eb4fb60fae30
		summarizeBy: none
		sourceColumn: Extra Care Status

		annotation SummarizationSetBy = Automatic

	column 'Extra Care Sales Amount Inc Gst'
		dataType: double
		lineageTag: 1caa1966-ed07-400f-836f-0e8fff85205f
		summarizeBy: sum
		sourceColumn: Extra Care Sales Amount Inc Gst

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column COUNTRY_ID
		dataType: double
		lineageTag: 57f41609-bfaf-4051-88de-a597ab65f08f
		summarizeBy: none
		sourceColumn: COUNTRY_ID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SALE_CHANNEL_ID
		dataType: double
		lineageTag: 6d9e4aa8-ed0e-4778-a379-94cf37a24375
		summarizeBy: count
		sourceColumn: SALE_CHANNEL_ID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SUB_SALE_CHANNEL_ID
		dataType: double
		lineageTag: ba5da67f-56b3-46e3-8a7a-2498af40eadc
		summarizeBy: none
		sourceColumn: SUB_SALE_CHANNEL_ID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column COUNTRY_PRIMARY_WRITTEN_SALE_STORE_ID
		dataType: string
		lineageTag: 90f4260d-e076-4c7a-923e-d8a1316b9e6f
		summarizeBy: none
		sourceColumn: COUNTRY_PRIMARY_WRITTEN_SALE_STORE_ID

		annotation SummarizationSetBy = Automatic

	column COUNTRY_EXTRA_CARE_STORE_ID
		dataType: string
		lineageTag: 2f083a71-43a2-4922-9480-7981bd7612fe
		summarizeBy: none
		sourceColumn: COUNTRY_EXTRA_CARE_STORE_ID

		annotation SummarizationSetBy = Automatic

	column Pctg
		dataType: double
		lineageTag: 679529d2-eec1-4071-aa9d-3593b999842f
		summarizeBy: sum
		sourceColumn: Pctg

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Not Sold On Pda'
		dataType: double
		lineageTag: 2c9c1d2f-4a64-4754-b6f8-4177117b6978
		summarizeBy: sum
		sourceColumn: Not Sold On Pda

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Error Overcharged Extra Care Pricing'
		dataType: double
		lineageTag: 55499abb-2807-47f0-afa9-52adc2580962
		summarizeBy: sum
		sourceColumn: Error Overcharged Extra Care Pricing

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Error Manual Refund'
		dataType: int64
		lineageTag: 99b9d488-c1a0-408a-b9a1-808cfac6c739
		summarizeBy: sum
		sourceColumn: Error Manual Refund

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Customer Firstname'
		dataType: string
		lineageTag: 52a651ca-16e0-4346-981b-b73d1a6b4f32
		summarizeBy: none
		sourceColumn: Customer Firstname

		annotation SummarizationSetBy = Automatic

	column 'Customer Lastname'
		dataType: string
		lineageTag: 24c7ff70-d780-48f3-907f-b1079e4e6320
		summarizeBy: none
		sourceColumn: Customer Lastname

		annotation SummarizationSetBy = Automatic

	column 'Customer Email'
		dataType: string
		lineageTag: efabf33d-6569-464e-90d1-a9d3927c7cec
		summarizeBy: none
		sourceColumn: Customer Email

		annotation SummarizationSetBy = Automatic

	column 'Customer Phonenumber'
		dataType: string
		lineageTag: d1726e4c-4043-46ab-bfd4-2b4587f38f11
		summarizeBy: none
		sourceColumn: Customer Phonenumber

		annotation SummarizationSetBy = Automatic

	column 'Return Errors' =
			
			VAR _RefundErrors =
			    IF(
			        'Sales and Return Errors'[Error Manual Refund] = 1,
			        "Manual Refunds",
			        BLANK()
			    )
			
			VAR _Discrepancy =
			    CONCATENATEX(
			        {
			            _RefundErrors
			        },
			        [Value]
			    )
			
			VAR _DiscrepancyCount =
			    [Error Manual Refund]
			
			RETURN
			    IF(_DiscrepancyCount > 1, "Multiple", _Discrepancy)
		lineageTag: aba0f905-a1bf-476d-a028-05098de113d4
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Error Type' =
			
			VAR ErrorCount =
			    [Error Ineligible From Manufacturers Warranty]
			    + [Error Overcharged Extra Care Pricing]
			    + [Not Sold On Pda]
			    + [ERROR_INCORRECT_EXTRA_CARE_STOCK_CODE]
			    + [Error Manual Refund]
			    + [ERROR_EXCLUDED_PRIMARY_STOCK_CODE]
			RETURN
			    SWITCH(
			        TRUE(),
			        ErrorCount > 1, "Multiple",
			        [Error Ineligible From Manufacturers Warranty] = 1, "Manufacturers Warranty",
			        [Error Overcharged Extra Care Pricing] = 1, "Incorrectly Charged for EC",
			        [Not Sold On Pda] = 1, "JBEC Not Sold On PDA",
			        [ERROR_INCORRECT_EXTRA_CARE_STOCK_CODE] = 1, "Wrong EC SKU Sold",
			        [Error Manual Refund] = 1, "Manually Returned",
			        [ERROR_EXCLUDED_PRIMARY_STOCK_CODE] = 1, "Excluded Primary SKUs",
			        BLANK()
			    )
		lineageTag: c6406995-a547-4ecf-ad45-241fb47fa789
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Voucher Discount Amt'
		dataType: double
		lineageTag: 7b310e5e-fffa-4b0b-b3d6-a60e50cc0259
		summarizeBy: sum
		sourceColumn: Voucher Discount Amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Mix And Match Discount Amt'
		dataType: double
		lineageTag: 84a76da2-930d-4e28-b941-aa78f423c3df
		summarizeBy: sum
		sourceColumn: Mix And Match Discount Amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Store Name'
		dataType: string
		lineageTag: 3eee6d76-5ae2-438a-b4b5-d5737af473ad
		summarizeBy: none
		sourceColumn: Store Name

		annotation SummarizationSetBy = Automatic

	column Employee_ID
		dataType: string
		lineageTag: b3ffa7c4-9e76-47c4-80da-8d1d21b26651
		summarizeBy: none
		sourceColumn: Employee_ID

		annotation SummarizationSetBy = Automatic

	column Primary_SKUs
		dataType: string
		lineageTag: 46be5f79-ab26-4e2c-b4a7-77513bf8829e
		summarizeBy: none
		sourceColumn: Primary_SKUs

		annotation SummarizationSetBy = Automatic

	column 'Employee Name'
		dataType: string
		lineageTag: 715e1a7d-2927-4549-95d2-539dac94add2
		summarizeBy: none
		sourceColumn: Employee Name

		annotation SummarizationSetBy = Automatic

	column 'Area Desc'
		dataType: string
		lineageTag: fee6a968-685d-48a8-ba13-30c7a93104e1
		summarizeBy: none
		sourceColumn: Area Desc

		annotation SummarizationSetBy = Automatic

	column 'Return Errors_1' =
			
			VAR _RefundErrors =
			    IF(
			        'Sales and Return Errors'[Error Manual Refund] = 1,
			        "Manual Return",
			        BLANK()
			    )
			
			VAR _Discrepancy =
			    CONCATENATEX(
			        {
			            _RefundErrors
			        },
			        [Value]
			    )
			
			VAR _DiscrepancyCount =
			    [Error Manual Refund]
			
			RETURN
			    IF(_DiscrepancyCount > 1, "Multiple", _Discrepancy)
		lineageTag: 68eacc64-d050-44cb-8645-4b79b7f50b30
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Return Errors_2' =
			
			VAR _RefundErrors =
			    IF(
			        'Sales and Return Errors'[Error Manual Refund] = 1,
			        "Manually Returned",
			        BLANK()
			    )
			
			VAR _Discrepancy =
			    CONCATENATEX(
			        {
			            _RefundErrors
			        },
			        [Value]
			    )
			
			VAR _DiscrepancyCount =
			    [Error Manual Refund]
			
			RETURN
			    IF(_DiscrepancyCount > 1, "Multiple", _Discrepancy)
		lineageTag: bb18ec59-0535-4963-9422-f01864415640
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Sales and Return Errors' = m
		mode: import
		queryGroup: Facts
		source = ```
				let
				    Source = PowerPlatform.Dataflows([]),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"871ebbdc-2574-434b-a349-d31f770025c0" = Workspaces{[workspaceId="871ebbdc-2574-434b-a349-d31f770025c0"]}[Data],
				    #"065f9eff-8c97-4edf-8e6c-32f5847a470a" = #"871ebbdc-2574-434b-a349-d31f770025c0"{[dataflowId="065f9eff-8c97-4edf-8e6c-32f5847a470a"]}[Data],
				    FACT_EXTRA_CARE_ERROR_TRACKER_AU_ = #"065f9eff-8c97-4edf-8e6c-32f5847a470a"{[entity="FACT_EXTRA_CARE_ERROR_TRACKER_AU",version=""]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(FACT_EXTRA_CARE_ERROR_TRACKER_AU_,{{"Country ID", "COUNTRY_ID"}, {"Sale Channel ID", "SALE_CHANNEL_ID"}, {"Sub Sale Channel ID", "SUB_SALE_CHANNEL_ID"}, {"Country Primary Written Sale Store ID", "COUNTRY_PRIMARY_WRITTEN_SALE_STORE_ID"}, {"Country Extra Care Store ID", "COUNTRY_EXTRA_CARE_STORE_ID"}}),
				    #"Reorder Columns" = Table.SelectColumns ( #"Renamed Columns", 
				            let
				                varBufferedList = List.Buffer ( Table.ColumnNames ( #"Renamed Columns" ) ),
				                varKeyColumns = List.Select ( varBufferedList, each Text.Contains ( _, "_KEY" ) ),
				                varIdColumns = List.Select ( varBufferedList, each Text.Contains ( _, "_ID" ) ),
				                varCodeColumns = List.Select ( varBufferedList, each Text.Contains ( _, "_CODE" ) ),
				                varAllOtherColumns = List.Select ( varBufferedList, each not Text.Contains ( _, "_KEY" ) and not Text.Contains ( _, "_ID" ) and not Text.Contains ( _, "_CODE" ) ),
				                varFinalColumns = List.Combine ( {varKeyColumns, varIdColumns, varCodeColumns, varAllOtherColumns} ) 
				            in
				                varFinalColumns
				            ),
				  #"Replaced Underscore" = Table.TransformColumnNames(#"Reorder Columns" , each
				    if Text.Contains(_, "_KEY") or Text.Contains(_, "_ID") or Text.Contains(_, "_STOCK_CODE") or Text.Contains(_, "_EMPLOYEE_CODE") then Text.Upper(_)
				    else Text.Proper(Text.Replace(_, "_", " "))
				    ),
				    #"Filtered Rows" = Table.SelectRows(#"Replaced Underscore", each [COUNTRY_ID] = COUNTRY_ID),
				    #"Removed Other Columns" = Table.SelectColumns(#"Filtered Rows",{"COUNTRY_ID", "SALE_CHANNEL_ID", "SUB_SALE_CHANNEL_ID", "COUNTRY_PRIMARY_WRITTEN_SALE_STORE_ID", "COUNTRY_EXTRA_CARE_STORE_ID", "COUNTRY_PRIMARY_EMPLOYEE_CODE", "COUNTRY_PRIMARY_STOCK_CODE", "COUNTRY_EXTRA_CARE_EMPLOYEE_CODE", "Employee Name", "COUNTRY_EXTRA_CARE_STOCK_CODE", "ERROR_INCORRECT_EXTRA_CARE_STOCK_CODE", "ERROR_EXCLUDED_PRIMARY_STOCK_CODE", "Written Sales Date", "Written Reference", "Delivered Reference", "Order Line Item", "Extra Care Status", "Reversed Transaction", "Primary Quantity", "Primary Sale Price", "Primary Sale Amount Inc Gst", "Extra Care Quantity", "Extra Care Sales Amount Inc Gst", "Extra Care Sale Price", "Not Sold On Pda", "Error Overcharged Extra Care Pricing", "Pctg", "Error Ineligible From Manufacturers Warranty","Error Manual Refund","Customer Firstname","Customer Lastname", "Customer Email", "Customer Phonenumber", "Voucher Discount Amt", "Mix And Match Discount Amt"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Other Columns",{{"Error Manual Refund", Int64.Type}, {"ERROR_EXCLUDED_PRIMARY_STOCK_CODE", Int64.Type}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type", {"COUNTRY_EXTRA_CARE_STORE_ID"}, Store, {"COUNTRY_STORE_ID"}, "Store", JoinKind.LeftOuter),
				    #"Expanded Store" = Table.ExpandTableColumn(#"Merged Queries", "Store", {"Store Name", "Area Desc"}, {"Store.Store Name", "Store.Area Desc"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Expanded Store",{{"Store.Store Name", "Store Name"}, {"Store.Area Desc", "Area Desc"}}),
				    #"Added Custom" = Table.AddColumn(#"Renamed Columns1", "Employee_ID", each Text.AfterDelimiter(Text.From([COUNTRY_PRIMARY_EMPLOYEE_CODE]), "_")),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Primary_SKUs", each Text.AfterDelimiter(Text.From([COUNTRY_PRIMARY_STOCK_CODE]), "_"))
				in
				    #"Added Custom1"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

