table 'Selling Channel'
	lineageTag: f9dbb14e-ea56-4893-b14a-c1fcbbe91ad3

	column SALE_CHANNEL_ID
		dataType: double
		isHidden
		lineageTag: 73fdef4d-ac40-495b-b92c-53289a0edf39
		summarizeBy: none
		sourceColumn: SALE_CHANNEL_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SUB_SALE_CHANNEL_ID
		dataType: double
		isHidden
		lineageTag: 1a104875-16e4-4d22-a169-dddb43c5fb44
		summarizeBy: none
		sourceColumn: SUB_SALE_CHANNEL_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Sale Channel'
		dataType: string
		lineageTag: d49f5f53-e33f-4a01-8550-2276d60881c6
		summarizeBy: none
		sourceColumn: Sale Channel

		annotation SummarizationSetBy = Automatic

	column 'Sale Channel Desc'
		dataType: string
		lineageTag: 9bdf32ac-2541-430a-9f27-bddf0309b09d
		summarizeBy: none
		sourceColumn: Sale Channel Desc

		annotation SummarizationSetBy = Automatic

	column 'Sub Sale Channel'
		dataType: string
		lineageTag: 0e718d15-ef1e-4002-8e49-78694e2a6337
		summarizeBy: none
		sourceColumn: Sub Sale Channel

		annotation SummarizationSetBy = Automatic

	column 'Sub Sale Channel Desc'
		dataType: string
		lineageTag: 680e1a0c-dd1f-4452-b9b8-9d5ae2cfc329
		summarizeBy: none
		sourceColumn: Sub Sale Channel Desc

		annotation SummarizationSetBy = Automatic

	column Active
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 0490397b-1f3a-4fd7-8237-35cb6950ba8e
		summarizeBy: none
		sourceColumn: Active

		annotation SummarizationSetBy = Automatic

	partition 'Selling Channel' = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"381214d4-ea63-4a86-87da-8aebf81978ae" = Workspaces{[workspaceId="381214d4-ea63-4a86-87da-8aebf81978ae"]}[Data],
				    #"c8f09baa-dbd9-401b-8d55-1801f53ef645" = #"381214d4-ea63-4a86-87da-8aebf81978ae"{[dataflowId="c8f09baa-dbd9-401b-8d55-1801f53ef645"]}[Data],
				    #"Selling Channel_" = #"c8f09baa-dbd9-401b-8d55-1801f53ef645"{[entity="Selling Channel",version=""]}[Data],
				    #"Merged Queries" = Table.NestedJoin(#"Selling Channel_", {"SUB_SALE_CHANNEL_ID"}, #"Sales and Return Errors", {"SUB_SALE_CHANNEL_ID"}, "Sales and Return Errors", JoinKind.Inner),
				    #"Removed Other Columns" = Table.SelectColumns(#"Merged Queries",{"SALE_CHANNEL_ID", "SUB_SALE_CHANNEL_ID", "Sale Channel", "Sale Channel Desc", "Sub Sale Channel", "Sub Sale Channel Desc", "Active"})
				in
				    #"Removed Other Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

