table Store
	lineageTag: e0b51985-2a4d-46f5-a2ae-8d31f4325bb9

	column COUNTRY_STORE_ID
		dataType: string
		isHidden
		lineageTag: 59fe69e8-0d1c-4baf-b526-561796ec3609
		summarizeBy: none
		sourceColumn: COUNTRY_STORE_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column COUNTRY_ID
		dataType: double
		isHidden
		lineageTag: 54ec4717-1097-4399-bef1-3e9092b30886
		summarizeBy: count
		sourceColumn: COUNTRY_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column STORE_ID
		dataType: double
		lineageTag: 382e2deb-a44e-4e42-8f09-76db6bddfe65
		summarizeBy: count
		sourceColumn: STORE_ID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column COUNTRY_AREA_MANAGER_ID
		dataType: string
		isHidden
		lineageTag: 6a56aff1-a749-41e1-9f72-4a78f0335028
		summarizeBy: none
		sourceColumn: COUNTRY_AREA_MANAGER_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AREA_MANAGER_ID
		dataType: string
		lineageTag: 839ff753-cd3f-40b7-9146-5f21a0c0fc0f
		summarizeBy: none
		sourceColumn: AREA_MANAGER_ID

		annotation SummarizationSetBy = Automatic

	column 'Store Name'
		dataType: string
		lineageTag: 2cf6bf72-5ae3-420b-9fe9-432a0b368556
		summarizeBy: none
		sourceColumn: Store Name

		annotation SummarizationSetBy = Automatic

	column 'Sub Type'
		dataType: string
		lineageTag: 7973a120-0021-4626-8398-f2819fee3544
		summarizeBy: none
		sourceColumn: Sub Type

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 6d480a48-2fed-4933-adc1-19c45ba9ee78
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Store Is Active'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 83550c2f-5ad0-4350-bd76-68da3fab4929
		summarizeBy: none
		sourceColumn: Store Is Active

		annotation SummarizationSetBy = Automatic

	column 'Start Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: da81c505-627a-44ad-a21b-218aa24bc57d
		summarizeBy: none
		sourceColumn: Start Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Finish Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: f3a0ef3e-b8b1-4cd7-84e5-4f7cb3042dbc
		summarizeBy: none
		sourceColumn: Finish Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Area Desc'
		dataType: string
		lineageTag: a13c6881-db7b-4dbb-b870-c7d5eceae9b9
		summarizeBy: none
		sourceColumn: Area Desc

		annotation SummarizationSetBy = Automatic

	partition Store = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"381214d4-ea63-4a86-87da-8aebf81978ae" = Workspaces{[workspaceId="381214d4-ea63-4a86-87da-8aebf81978ae"]}[Data],
				    #"c8f09baa-dbd9-401b-8d55-1801f53ef645" = #"381214d4-ea63-4a86-87da-8aebf81978ae"{[dataflowId="c8f09baa-dbd9-401b-8d55-1801f53ef645"]}[Data],
				    Store_ = #"c8f09baa-dbd9-401b-8d55-1801f53ef645"{[entity="Store",version=""]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(Store_,{"COUNTRY_STORE_ID", "COUNTRY_ID", "STORE_ID", "COUNTRY_AREA_MANAGER_ID", "AREA_MANAGER_ID", "Store Name", "Sub Type", "State", "Store Is Active", "Start Date", "Finish Date", "Area Desc"}),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Other Columns", each ([COUNTRY_ID] = COUNTRY_ID))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

